### ISSUE TITLE
Concorrencia, Elixir ou Go?

### ISSUE THREAD

**Issue by Halfeld** [pp-project/subjects#1]
Trazer dois convidados que usam ativamente uma das linguagens para fazer um diálogo maturo. Trocando aquela ideia pra gente entender o propósito da linguagem, como eles usam a concorrencia delas, e onde aplicar cada uma.

**Comment by gugahoa** [comment]
Ambas as linguagens sendo extremamente competentes na questão de concorrencia, sempre me perguntei quais são as áreas em que Elixir brilha e em que Go brilha.   

Resumindo em uma pergunta seria: Qual o problema de concorrencia que Elixir é a melhor escolha, e qual o problema de concorrencia que Go é a melhor escola?

**Comment by julioc98** [comment]
Bom tema quero ouvir isso ai....

**Comment by Halfeld** [comment]
Piloto lançado: https://soundcloud.com/user-663337641/concorrencia-elixir-ou-go

**Comment by julioc98** [comment]
@Halfeld  nem me convidou...deixa você.... kkkkkkk
